#配置文件，请根据介绍填写相关配置

#使用的配置:

#用户配置
user: 
#机器人主人QQ,只有一位
  admin: ""

#管理员QQ,可以有多位
  manager: [""]

#昵称(触发助手的关键词)
nickname: ["助手","amadeus"]

web: 
  host: "127.0.0.1"
  port: 8901



#调试的配置(一般用不上):
#日志等级
log_level: "INFO"